application_dir = "maya"
default_dirs = [
	"scenes",
	"data",
	"renderData/shaders",
	"images"
]
label = "Autodesk Maya 2019"
schema = "avalon-core:application-1.0"
executable = "maya_2019"
description = ""

[copy]
"{AVALON_CORE}/res/workspace.mel" = "workspace.mel"

[environment]
MAYA_DISABLE_CLIC_IPM = "Yes"  # Disable the AdSSO process
MAYA_DISABLE_CIP = "Yes"  # Shorten time to boot
MAYA_DISABLE_CER = "Yes"
PYMEL_SKIP_MEL_INIT = "Yes"
LC_ALL= "C"  # Mute color management warnings
PYTHONPATH = [
	"{AVALON_CORE}/setup/maya",
	"{PYTHONPATH}"
]
