application_dir = "maya"
default_dirs = [
	"scenes",
	"data",
	"renderData/shaders",
	"images"
]
label = "Autodesk MayaPy 2016"
schema = "avalon-core:application-1.0"
executable = "mayapy2016"
description = ""

[copy]
"{AVALON_CORE}/res/workspace.mel" = "workspace.mel"

[environment]
PYTHONPATH = [
	"{AVALON_CORE}/setup/maya",
	"{PYTHONPATH}"
]
