application_dir = "maya"
default_dirs = [
	"scenes",
	"data",
	"renderData/shaders",
	"images"
]
label = "Autodesk Maya 2017x64"
schema = "avalon-core:application-1.0"
executable = "mayapy2017"
description = ""

[copy]
"{AVALON_CORE}/res/workspace.mel" = "workspace.mel"

[environment]
PYTHONPATH = [
	"{AVALON_CORE}/setup/maya",
	"{PYTHONPATH}"
]
