executable = "nukestudio11.0v4"
schema = "avalon-core:application-1.0"
application_dir = "nuke"
label = "The Foundry NukeStudio 11.0v4"

[environment]
NUKE_PATH = ["{AVALON_CORE}/setup/nuke/nuke_path"]
